import 'package:flutter/material.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedNav_textWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedBaseWidget1.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedTimerLightWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedHoraspedaladasWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedUsersalt1Widget4.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedRectangle33Widget3.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedGridiconsstatsWidget4.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedIconStopwatchWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedOSstatusBarsonLightWidget13.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedGroup68Widget4.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedNavbtnWidget1.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedRectangle26Widget4.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedTaskCompletedLightWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/Generated3h46mWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/voudebikeapp/generatedestatsticaswidget/generated/GeneratedAntdesigninfocirclefilledWidget4.dart';

/* Frame estatísticas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEstatsticasWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 249, 248, 253),
                ),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: null,
                bottom: 0.0,
                width: 373.0,
                height: 65.0,
                child: GeneratedRectangle26Widget4(),
              ),
              Positioned(
                left: 38.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup68Widget4(),
              ),
              Positioned(
                left: 238.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUsersalt1Widget4(),
              ),
              Positioned(
                left: 307.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 47.0,
                child: GeneratedAntdesigninfocirclefilledWidget4(),
              ),
              Positioned(
                left: 122.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 36.0,
                child: GeneratedRectangle33Widget3(),
              ),
              Positioned(
                left: 138.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGridiconsstatsWidget4(),
              ),
              Positioned(
                left: 21.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 132.0,
                child: GeneratedTaskCompletedLightWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedNavbtnWidget1(),
              ),
              Positioned(
                left: 198.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 132.0,
                child: GeneratedBaseWidget1(),
              ),
              Positioned(
                left: 214.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 34.0,
                child: Generated3h46mWidget(),
              ),
              Positioned(
                left: 256.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedHoraspedaladasWidget(),
              ),
              Positioned(
                left: 216.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedIconStopwatchWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 44.0,
                child: GeneratedOSstatusBarsonLightWidget13(),
              ),
              Positioned(
                left: 21.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 504.0,
                child: GeneratedTimerLightWidget(),
              ),
              Positioned(
                left: null,
                top: 50.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 25.0,
                child: TransformHelper.translate(
                    x: 7.50, y: 0.00, z: 0, child: GeneratedNav_textWidget()),
              )
            ]),
      ),
    ));
  }
}
