import 'package:flutter/material.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedPrincipalctaWidget8.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedEmailWidget2.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedShapeWidget2.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedTopWidget1.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedEsqueceuasenhaWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedBoxWidget13.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedPasswordWidget3.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedBoxWidget14.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedOShomeIndicatioronLightWidget7.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedExampleWidget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedOSstatusBarsonLightWidget7.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox3widget/generated/GeneratedExampleWidget10.dart';

/* Frame iPhone 11 Pro / X - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 249, 248, 253),
                      ),
                    ),
                    Positioned(
                      left: -210.0,
                      top: -404.0,
                      right: null,
                      bottom: null,
                      width: 700.0,
                      height: 700.0,
                      child: GeneratedTopWidget1(),
                    ),
                    Positioned(
                      left: -20.0,
                      top: 847.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 49.0,
                      child: GeneratedOShomeIndicatioronLightWidget7(),
                    ),
                    Positioned(
                      left: 220.0,
                      top: 513.0,
                      right: null,
                      bottom: null,
                      width: 130.0,
                      height: 19.0,
                      child: GeneratedEsqueceuasenhaWidget(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 461.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 48.0,
                      child: GeneratedBoxWidget13(),
                    ),
                    Positioned(
                      left: 53.533447265625,
                      top: 475.0,
                      right: null,
                      bottom: null,
                      width: 241.86666870117188,
                      height: 25.0,
                      child: GeneratedExampleWidget9(),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 439.0,
                      right: null,
                      bottom: null,
                      width: 47.0,
                      height: 22.0,
                      child: GeneratedPasswordWidget3(),
                    ),
                    Positioned(
                      left: 320.0,
                      top: 479.0,
                      right: null,
                      bottom: null,
                      width: 18.0,
                      height: 11.0,
                      child: GeneratedShapeWidget2(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 382.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 48.0,
                      child: GeneratedBoxWidget14(),
                    ),
                    Positioned(
                      left: 53.533447265625,
                      top: 396.0,
                      right: null,
                      bottom: null,
                      width: 228.94667053222656,
                      height: 25.0,
                      child: GeneratedExampleWidget10(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 360.0,
                      right: null,
                      bottom: null,
                      width: 41.0,
                      height: 22.0,
                      child: GeneratedEmailWidget2(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.4826666666666667;

                        final double height =
                            constraints.maxHeight * 0.0665024630541872;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.2613333333333333,
                              y: constraints.maxHeight * 0.7253694581280788,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedPrincipalctaWidget8(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedOSstatusBarsonLightWidget7(),
            )
          ]),
    ));
  }
}
