description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Slabo 13px"
      fonts: 
        - 
          asset: "fonts/Slabo13px-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-900.ttf"
          style: "normal"
          weight: 900
        - 
          asset: "fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Poppins-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Public Sans"
      fonts: 
        - 
          asset: "fonts/PublicSans-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Rubik"
      fonts: 
        - 
          asset: "fonts/Rubik-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Rubik-500.ttf"
          style: "normal"
          weight: 500
  uses-material-design: true
