import 'package:flutter/material.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox2widget/generated/GeneratedSlider_dotsWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox2widget/generated/GeneratedOShomeIndicatioronLightWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox2widget/generated/GeneratedPrincipalctaWidget2.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox2widget/generated/GeneratedEstudosindicamqueaotriplicaronmerodeciclistasnasruasapo.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox2widget/generated/GeneratedVOUDEBIKEWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox2widget/generated/GeneratedDownload2Widget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox2widget/generated/GeneratedOSstatusBarsonLightWidget4.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox2widget/generated/GeneratedPrincipalctaWidget3.dart';

/* Frame iPhone 11 Pro / X - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 249, 248, 253),
                ),
              ),
              Positioned(
                left: -20.0,
                top: 847.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 49.0,
                child: GeneratedOShomeIndicatioronLightWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4826666666666667;

                  final double height =
                      constraints.maxHeight * 0.0665024630541872;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.25866666666666666,
                        y: constraints.maxHeight * 0.43226600985221675,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPrincipalctaWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4826666666666667;

                  final double height =
                      constraints.maxHeight * 0.0665024630541872;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.25866666666666666,
                        y: constraints.maxHeight * 0.5233990147783252,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPrincipalctaWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 44.0,
                child: GeneratedOSstatusBarsonLightWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.38133333333333336;

                  final double height =
                      constraints.maxHeight * 0.10714285714285714;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.31733333333333336,
                        y: constraints.maxHeight * 0.17857142857142858,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDownload2Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 80.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 41.0,
                child: GeneratedVOUDEBIKEWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 285.0,
                height: 134.0,
                child:
                    GeneratedEstudosindicamqueaotriplicaronmerodeciclistasnasruasapo(),
              ),
              Positioned(
                left: 142.0,
                top: 738.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 8.0,
                child: GeneratedSlider_dotsWidget(),
              )
            ]),
      ),
    ));
  }
}
