import 'package:flutter/material.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedculosWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedSuapontuaoComsuapontuaovocobtercuponsparatrocaremlojasW.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedChecklistdeseguranaWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedOSstatusBarsonLightWidget8.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedUnstartedWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedUnstartedWidget5.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/Generated00Widget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedCapaceteWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedUnstartedWidget3.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedUnstartedWidget1.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedUnstartedWidget2.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedRefletoresWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedUnstartedWidget4.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedPrincipalctaWidget9.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedNavbtnWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedOShomeIndicatioronLightWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedLuvaseproteesWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedSinalizaonoturnaWidget.dart';
import 'package:flutterapp/voudebikeapp/generatediphone11prox6widget/generated/GeneratedConferirosespelhosebuzinaWidget.dart';

/* Frame iPhone 11 Pro / X - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 249, 248, 253),
                      ),
                    ),
                    Positioned(
                      left: -20.0,
                      top: 847.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 49.0,
                      child: GeneratedOShomeIndicatioronLightWidget8(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 134.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedUnstartedWidget(),
                    ),
                    Positioned(
                      left: 84.0,
                      top: 0.0,
                      right: -60.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double height =
                            constraints.maxHeight * 0.04310344827586207;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.16502463054187191,
                              z: 0,
                              child: Container(
                                height: height,
                                child: GeneratedCapaceteWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 192.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedUnstartedWidget1(),
                    ),
                    Positioned(
                      left: 84.0,
                      top: 0.0,
                      right: -57.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double height =
                            constraints.maxHeight * 0.03940886699507389;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.23645320197044334,
                              z: 0,
                              child: Container(
                                height: height,
                                child: GeneratedLuvaseproteesWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 250.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedUnstartedWidget2(),
                    ),
                    Positioned(
                      left: 84.0,
                      top: 0.0,
                      right: -60.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double height =
                            constraints.maxHeight * 0.04310344827586207;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.3078817733990148,
                              z: 0,
                              child: Container(
                                height: height,
                                child: GeneratedculosWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 308.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedUnstartedWidget3(),
                    ),
                    Positioned(
                      left: 84.0,
                      top: 0.0,
                      right: -60.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double height =
                            constraints.maxHeight * 0.04310344827586207;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.3793103448275862,
                              z: 0,
                              child: Container(
                                height: height,
                                child: GeneratedRefletoresWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 370.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedUnstartedWidget4(),
                    ),
                    Positioned(
                      left: 84.0,
                      top: 0.0,
                      right: -57.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double height =
                            constraints.maxHeight * 0.03940886699507389;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.45566502463054187,
                              z: 0,
                              child: Container(
                                height: height,
                                child: GeneratedSinalizaonoturnaWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 433.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedUnstartedWidget5(),
                    ),
                    Positioned(
                      left: 84.0,
                      top: 0.0,
                      right: -57.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double height =
                            constraints.maxHeight * 0.03940886699507389;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.5332512315270936,
                              z: 0,
                              child: Container(
                                height: height,
                                child:
                                    GeneratedConferirosespelhosebuzinaWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 27.0,
                      top: 44.0,
                      right: null,
                      bottom: null,
                      width: 36.0,
                      height: 36.0,
                      child: GeneratedNavbtnWidget(),
                    ),
                    Positioned(
                      left: 92.0,
                      top: 52.0,
                      right: null,
                      bottom: null,
                      width: 193.0,
                      height: 23.0,
                      child: GeneratedChecklistdeseguranaWidget(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 604.0,
                      right: null,
                      bottom: null,
                      width: 320.0,
                      height: 115.0,
                      child:
                          GeneratedSuapontuaoComsuapontuaovocobtercuponsparatrocaremlojasW(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.42933333333333334;

                        final double height =
                            constraints.maxHeight * 0.05541871921182266;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.2853333333333333,
                              y: constraints.maxHeight * 0.6477832512315271,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedPrincipalctaWidget9(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 157.0,
                      top: 640.0,
                      right: null,
                      bottom: null,
                      width: 69.0,
                      height: 37.0,
                      child: Generated00Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedOSstatusBarsonLightWidget8(),
            )
          ]),
    ));
  }
}
