import 'package:flutter/material.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedQuaselWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedBoxWidget3.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedBoxWidget2.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedOShomeIndicatioronLightWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedEnviamosumemailparamariasilvemailcomInsiraocdigodeverif.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedBoxWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedBoxWidget1.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedNavigate_before24px1Widget.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedOSstatusBarsonLightWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedsignupconfirmationwidget/generated/GeneratedReenviarcdigoem0023Widget.dart';

/* Frame Sign Up Confirmation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpConfirmationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 249, 248, 253),
                      ),
                    ),
                    Positioned(
                      left: -280.0,
                      top: -589.0,
                      right: null,
                      bottom: null,
                      width: 846.0,
                      height: 953.0,
                      child: GeneratedEllipse1Widget(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 125.0,
                      right: null,
                      bottom: null,
                      width: 325.0,
                      height: 46.0,
                      child: GeneratedQuaselWidget(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 202.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 112.0,
                      child:
                          GeneratedEnviamosumemailparamariasilvemailcomInsiraocdigodeverif(),
                    ),
                    Positioned(
                      left: 24.0,
                      top: 48.0,
                      right: null,
                      bottom: null,
                      width: 48.0,
                      height: 48.0,
                      child: GeneratedNavigate_before24px1Widget(),
                    ),
                    Positioned(
                      left: 127.0,
                      top: 473.0,
                      right: null,
                      bottom: null,
                      width: 49.0,
                      height: 49.0,
                      child: GeneratedBoxWidget(),
                    ),
                    Positioned(
                      left: 199.0,
                      top: 473.0,
                      right: null,
                      bottom: null,
                      width: 49.0,
                      height: 49.0,
                      child: GeneratedBoxWidget1(),
                    ),
                    Positioned(
                      left: 271.0,
                      top: 473.0,
                      right: null,
                      bottom: null,
                      width: 49.0,
                      height: 49.0,
                      child: GeneratedBoxWidget2(),
                    ),
                    Positioned(
                      left: 55.0,
                      top: 473.0,
                      right: null,
                      bottom: null,
                      width: 49.0,
                      height: 49.0,
                      child: GeneratedBoxWidget3(),
                    ),
                    Positioned(
                      left: 93.0,
                      top: 602.0,
                      right: null,
                      bottom: null,
                      width: 190.0,
                      height: 22.0,
                      child: GeneratedReenviarcdigoem0023Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 778.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 34.0,
                      child: GeneratedOShomeIndicatioronLightWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedOSstatusBarsonLightWidget(),
            )
          ]),
    ));
  }
}
