import 'package:flutter/material.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedOShomeIndicatioronLightWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedNavigate_before24px1Widget2.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedNoWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedAssinaleseverdadeirooufalso1UsarcapaceteobrigatrioWidge.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedComponentsRadioButtonActiveWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedComponentsRadioButtonInactiveWidget2.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedSimWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/Generated0pontosWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedPontuaoWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedQuizWidget3.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedPrincipalctaWidget1.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget2/generated/GeneratedOSstatusBarsonLightWidget2.dart';

/* Frame quiz
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQuizWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 249, 248, 253),
                      ),
                    ),
                    Positioned(
                      left: -198.0,
                      top: -589.0,
                      right: null,
                      bottom: null,
                      width: 764.0,
                      height: 875.0,
                      child: GeneratedEllipse1Widget2(),
                    ),
                    Positioned(
                      left: 152.0,
                      top: 52.0,
                      right: null,
                      bottom: null,
                      width: 100.0,
                      height: 49.0,
                      child: GeneratedQuizWidget3(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 318.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 46.0,
                      child:
                          GeneratedAssinaleseverdadeirooufalso1UsarcapaceteobrigatrioWidge(),
                    ),
                    Positioned(
                      left: 24.0,
                      top: 48.0,
                      right: null,
                      bottom: null,
                      width: 48.0,
                      height: 48.0,
                      child: GeneratedNavigate_before24px1Widget2(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 778.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 34.0,
                      child: GeneratedOShomeIndicatioronLightWidget2(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.42933333333333334;

                        final double height =
                            constraints.maxHeight * 0.05541871921182266;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.2773333333333333,
                              y: constraints.maxHeight * 0.6440886699507389,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedPrincipalctaWidget1(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 48.0,
                      top: 394.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedComponentsRadioButtonActiveWidget(),
                    ),
                    Positioned(
                      left: 48.0,
                      top: 439.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedComponentsRadioButtonInactiveWidget2(),
                    ),
                    Positioned(
                      left: 95.0,
                      top: 394.0,
                      right: null,
                      bottom: null,
                      width: 36.0,
                      height: 26.0,
                      child: GeneratedSimWidget(),
                    ),
                    Positioned(
                      left: 95.0,
                      top: 441.0,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 26.0,
                      child: GeneratedNoWidget(),
                    ),
                    Positioned(
                      left: 84.0,
                      top: 181.0,
                      right: null,
                      bottom: null,
                      width: 220.0,
                      height: 34.0,
                      child: Generated0pontosWidget(),
                    ),
                    Positioned(
                      left: 40.0,
                      top: 149.0,
                      right: null,
                      bottom: null,
                      width: 318.0,
                      height: 27.0,
                      child: GeneratedPontuaoWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedOSstatusBarsonLightWidget2(),
            )
          ]),
    ));
  }
}
