import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget/generated/GeneratedQuizWidget1.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget/generated/GeneratedNavigate_before24px1Widget1.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget/generated/GeneratedPrincipalctaWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget/generated/GeneratedFlatWidget.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget/generated/GeneratedEssetestetemcomoobjetivoeducarsobreleisdireitosedeveres.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget/generated/GeneratedOShomeIndicatioronLightWidget1.dart';
import 'package:flutterapp/voudebikeapp/generatedquizwidget/generated/GeneratedOSstatusBarsonLightWidget1.dart';

/* Frame quiz
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQuizWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 249, 248, 253),
                      ),
                    ),
                    Positioned(
                      left: -198.0,
                      top: -589.0,
                      right: null,
                      bottom: null,
                      width: 764.0,
                      height: 928.0,
                      child: GeneratedEllipse1Widget1(),
                    ),
                    Positioned(
                      left: 152.0,
                      top: 52.0,
                      right: null,
                      bottom: null,
                      width: 100.0,
                      height: 49.0,
                      child: GeneratedQuizWidget1(),
                    ),
                    Positioned(
                      left: 40.0,
                      top: 113.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 178.0,
                      child:
                          GeneratedEssetestetemcomoobjetivoeducarsobreleisdireitosedeveres(),
                    ),
                    Positioned(
                      left: 24.0,
                      top: 48.0,
                      right: null,
                      bottom: null,
                      width: 48.0,
                      height: 48.0,
                      child: GeneratedNavigate_before24px1Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 778.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 34.0,
                      child: GeneratedOShomeIndicatioronLightWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.42933333333333334;

                        final double height =
                            constraints.maxHeight * 0.05541871921182266;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.2853333333333333,
                              y: constraints.maxHeight * 0.5024630541871922,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedPrincipalctaWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 0.344;

                        final double height =
                            constraints.maxHeight * 0.15885808784973446;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.352,
                              y: constraints.maxHeight * 0.6083743842364532,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedFlatWidget(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedOSstatusBarsonLightWidget1(),
            )
          ]),
    ));
  }
}
