import 'package:flutter/material.dart';
import 'package:flutterapp/voudebikeapp/generatedmapawidget1/generated/GeneratedVaidebikeAntesdissoconfiraachecklistdeseguranaadiciones.dart';
import 'package:flutterapp/voudebikeapp/generatedmapawidget1/generated/GeneratedPrincipalctaWidget10.dart';
import 'package:flutterapp/voudebikeapp/generatedmapawidget1/generated/GeneratedGroup70Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame mapa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMapaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/dc5c1a83f187fd13f8af270c1315ec9ad0eed28b.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 375.0,
                  height: 812.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 812.0,
                child: GeneratedGroup70Widget2(),
              ),
              Positioned(
                left: 51.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 107.0,
                child:
                    GeneratedVaidebikeAntesdissoconfiraachecklistdeseguranaadiciones(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.42933333333333334;

                  final double height =
                      constraints.maxHeight * 0.05541871921182266;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2906666666666667,
                        y: constraints.maxHeight * 0.8399014778325123,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPrincipalctaWidget10(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
