import 'package:flutter/material.dart';
import 'package:flutterapp/voudebikeapp/generatedroutewidget/generated/GeneratedRouteWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/voudebikeapp/generatedroutewidget/generated/GeneratedGroup70Widget.dart';

/* Frame route
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRouteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/dc5c1a83f187fd13f8af270c1315ec9ad0eed28b.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 375.0,
                  height: 812.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 812.0,
                child: GeneratedGroup70Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 325.0,
                height: 196.5,
                child: TransformHelper.translate(
                    x: 17.00, y: 0.25, z: 0, child: GeneratedRouteWidget1()),
              )
            ]),
      ),
    ));
  }
}
